version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: brr
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs_qr:/var/log/mysql
  app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/brr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      CONTAINER_NAME: spring-app
      CONTAINER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  mysql_data:
  mysql_logs_qr:
